### ISSUE TITLE
Can I use this to download all my notes?

### ISSUE THREAD

**Issue by ylluminarious** [contagon/ldsnotes#13]
Hi there,

Thanks for making this tool. It seems like it might be very useful for me in my current situation.

For years, I've had hundreds of notes on LDS.org. This includes annotations, highlights, and actual written notes. I never thought to download them until recently, since I've moved to other forms of note-taking than the the app / website. My notes have valuable insights and scriptures that I accrued when I was younger and I'd like to be able to download all these notes and look at them, if for nothing else than for posterity's sake.

Unfortunately, the current builtin function on the website is totally inadequate for downloading notes. The download button simply gives you a CSV file which is missing many notes and is not even properly encoded. [They used to have a better feature](https://tech.churchofjesuschrist.org/forum/viewtopic.php?f=101&t=20810) which would download DOCX, RTF, or XML files, but that is no longer available.

[Lots of people](https://tech.churchofjesuschrist.org/forum/search.php?st=0&sk=t&sd=d&sr=posts&keywords=export+notes) on the tech LDS forum have talked about how frustrating it is not to have a proper download function to export and view notes offline. Some examples can be found [here](https://tech.churchofjesuschrist.org/forum/viewtopic.php?f=19&t=11010), [here](https://tech.churchofjesuschrist.org/forum/viewtopic.php?f=19&t=11010&start=10), and [here.](https://tech.churchofjesuschrist.org/forum/viewtopic.php?f=101&t=20810&start=20) Evidently, I'm not the only one struggling with the lack of a proper download function.

Is it possible for me to use this tool to export and download ALL of my LDS.org notes? I want to download all my highlights, annotations, written notes, bookmarks, everything. I can see this tool requires some scripting, which is fine - I'm a programmer. I'd just like to get a few pointers in the right direction to figure out how to properly download everything via this tool.

If I can't use this tool to do it, I'll probably have to manually download my notes myself, which will be a very long and tedious process that I hope to avoid. I'm also not sure if my some of my bookmarks are even visible on the actual website anymore, since there appears to be bookmarks appearing in my script output than what I see online. So I'm thinking this script might even be able to give me more complete output than what I can see online.

Any advice on how to do this would be appreciated.

Thanks.

**Comment by contagon** [comment]
Absolutely! This is exactly what it's made for.

You should be able to get ALL your notes, albeit a little slowly. [Here's an example on how to login and basic usage (and all the rest of the documentation).](https://ldsnotes.readthedocs.io/en/latest/usage.html)

Once you're logged in, you can access your notes via
```
first_10_notes = n[:10]
first_1000_notes = n[:1000]
```

These will be sorted by most recent, and I believe if you insert a number larger than your number of notes, it'll just return your all of notes.

[You can also search, I've tried to document the code pretty well.](https://github.com/contagon/ldsnotes/blob/master/ldsnotes/note.py#L177)

Let me know if you have any other questions! Let me know if you have any more questions, happy to help!

**Comment by ylluminarious** [comment]
@contagon That's awesome! Thanks for the link.

So I made a simple script (the same as what's in the example):

`download.py`
```py
#!/usr/bin/env python
from pprint import pprint
from ldsnotes import Notes

n = Notes("username", "password")

pprint(n[:10000])
```

I definitely have less than 10,000 notes, so I thought that would be a safe ceiling. Unfortunately, when I ran:

```sh
$ ./download.py > ldsnotes.txt
```

I got the following error:

```
Traceback (most recent call last):
  File "./download.py", line 7, in <module>
    pprint(n[:10000])
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/ldsnotes/note.py", line 175, in __getitem__
    url=ANNOTATIONS, params=params).json())
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/ldsnotes/annotations.py", line 33, in make_annotation
    annotations.append(Highlight(j, content))
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/ldsnotes/annotations.py", line 213, in __init__
    sep_content.append(clean_html(j['content'][0]['markup']))
KeyError: 'content'
```

I'm not sure what this means and I'm not an expert at Python, so I can't tell offhand. Could you help me figure out what's going on here?

**Comment by ylluminarious** [comment]
@contagon Hey again, not to be a bother, but do you have any advice for resolving the above error? 🙂

**Comment by ylluminarious** [comment]
@contagon Friendly ping 🙂

**Comment by ylluminarious** [comment]
@contagon Hmm, this crash seems to have something to do with the ceiling value. I tried fiddling with this again this weekend and when I set the `pprint` argument to `100` instead of `10000`, it actually worked. However, when I crank it up to `200`, that seems to break it. This is unfortunate as the number of my notes appears to be between 200 and 300 (not sure exactly how many).

Would definitely appreciate it if you could offer any advice or help on how to deal with this crash 🙂

**Comment by contagon** [comment]
Oh great! I'm guessing there's likely a note format that I haven't encountered before - it's been a pretty common theme when developing this. Next step is going to be finding exactly what note is causing the issue, something simple like the following should work:

```python
#!/usr/bin/env python
from pprint import pprint
from ldsnotes import Notes

n = Notes("username", "password")
for i in range(200):
    print(i)
    n[i]
```

Once you find the number we'll do some more digging :)

**Comment by ylluminarious** [comment]
@contagon Okay, great. Thanks for the explanation. I'll try to test that out within the next couple days or so and let you know how it goes.
